### ISSUE TITLE
Please upload project as .py

### ISSUE THREAD

**Issue by samohib** [tamanna037/InformationTypesDetectionNLP#9] opened 2022-10-22 00:37 UTC
Hi there! I am working on this repo for course work and am wondering if you can upload it as a .py file. If you could also split it into classes and methods so my group member and I can divide up work for creating test cases, it would be greatly appreciated.

**Comment by abarcomb-work** [comment] 2022-10-24 16:48
Duplicate of issue #6 - addressing this should be a priority.

**Comment by tamanna-sb** [comment] 2022-10-26 18:33
Hi I have  uploaded my code as py file ; also splitted the code in some methods.  
Also, I have changed the model , used huggingface transformer. And to handle class imbalance , i used class weight. I have added some good first issue. You can try working on those or anything you like.

**Closed as completed** 2022-10-26 18:34 UTC
